# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caca318c5df02cee771735ce267fdc1237a65ba3122c2c8116093805c273673de155e9b8c3a5e970a0484f8493cc5c3c8560facbcf67cbf4536de48040ef3cfc

test:
  secret_key_base: d10c102214bfc92375457afd93c81b12970f8d06069ea5e51e5a5f222004c9752ae5a1887643854eb912733fe436f72e04877ba0490f23d72a9e97fb8e96f2f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
